# Generated by Django 5.1.2 on 2024-12-09 16:11

import django.db.models.deletion
import fonction
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=fonction.get_image_upload_to)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=500)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('coordonne', models.TextField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('libelle', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Fournisseur'), (3, 'Autre')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=150, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('somme', models.IntegerField(default=0)),
                ('facture', models.FileField(blank=True, null=True, upload_to=fonction.get_facture_upload_to)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('coordonne', models.TextField(blank=True, null=True)),
                ('numero', models.CharField(max_length=20)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ref', models.CharField(max_length=150, unique=True)),
                ('libelle', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=fonction.get_facture_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=150, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('qte', models.IntegerField(default=0)),
                ('pu', models.IntegerField(default=0)),
                ('cumuler_quantite', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactEntre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('facture', models.FileField(blank=True, null=True, upload_to=fonction.get_facture_upload_to)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('facture', models.FileField(blank=True, null=True, upload_to=fonction.get_facture_upload_to)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueEntrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=150, unique=True)),
                ('qte', models.IntegerField()),
                ('pu', models.IntegerField()),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('libelle', models.CharField(blank=True, max_length=150, null=True)),
                ('categorie', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=150, unique=True)),
                ('qte', models.IntegerField()),
                ('pu', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('libelle', models.CharField(blank=True, max_length=150, null=True)),
                ('categorie', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=512, unique=True)),
                ('payer', models.BooleanField(default=False)),
                ('moyen_paiement', models.CharField(choices=[('Orange Money', 'Orange Money'), ('Moov Money', 'Moov Money'), ('Sama Money', 'Sama Money'), ('Carte Visa', 'Carte Visa')], max_length=50)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(null=True)),
                ('montant', models.FloatField()),
                ('numero', models.CharField(max_length=30, null=True)),
                ('strip_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref', models.CharField(max_length=150, unique=True)),
                ('qte', models.IntegerField(default=0)),
                ('pu', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=fonction.get_image_upload_to)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('qte', models.IntegerField(default=0)),
                ('pu', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.client')),
            ],
        ),
    ]
