# Generated by Django 5.1.2 on 2024-12-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_alter_historiqueentrer_ref_and_more'),
    ]

    operations = [
    ]
