# Generated by Django 5.1.2 on 2024-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_auto_20241210_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
