# Generated by Django 5.1.2 on 2024-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_alter_client_adresse_alter_client_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='libelle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
