# Generated by Django 5.1.2 on 2024-11-30 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_entreprise_libelle_alter_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueentrer',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise'),
        ),
    ]
