# Generated by Django 5.1.2 on 2024-12-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_alter_depense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='is_sortie',
            field=models.BooleanField(default=True),
        ),
    ]
