# Generated by Django 5.1.2 on 2024-12-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_entrer_is_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='somme',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entrer',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
