# Generated by Django 5.1.2 on 2024-12-05 12:04

import fonction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_paiemententreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fonction.get_image_upload_to),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fonction.get_image_upload_to),
        ),
    ]
