# Generated by Django 5.1.2 on 2024-12-07 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0008_categorie_image_souscategorie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('qte', models.IntegerField(default=0)),
                ('pu', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('souscategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.souscategorie')),
            ],
        ),
    ]
