# Generated by Django 5.1.2 on 2024-12-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0008_alter_depense_somme_alter_entrer_pu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='somme',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
