# Generated by Django 5.1.2 on 2024-12-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0009_alter_depense_somme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrer',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historiqueentrer',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historiquesortie',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
