# Generated by Django 5.1.2 on 2025-01-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0011_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='pu_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
