# Generated by Django 5.1.2 on 2025-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0012_entrer_pu_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='imageCodes/'),
        ),
    ]
