# Generated by Django 5.1.2 on 2025-02-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0013_entrer_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='entrer',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='entrer',
            name='number_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
