# Generated by Django 5.1.2 on 2025-02-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0015_alter_entrer_country_id_alter_entrer_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrer',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='entrer',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='entrer',
            name='number_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
