# Generated by Django 5.1.2 on 2025-02-02 21:23

import fonction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0016_alter_entrer_country_id_alter_entrer_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrer',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=fonction.get_image_upload_to),
        ),
    ]
