# Generated by Django 5.1.2 on 2025-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0018_avi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='is_remise',
            field=models.BooleanField(default=False),
        ),
    ]
