# Generated by Django 5.1.2 on 2025-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0019_sortie_is_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='is_prix',
            field=models.BooleanField(default=True),
        ),
    ]
