# Generated by Django 5.1.2 on 2025-03-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0021_alter_entrer_is_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrer',
            name='is_prix',
            field=models.BooleanField(default=True),
        ),
    ]
