# Generated by Django 5.1.2 on 2025-03-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0022_alter_entrer_is_prix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
