# Generated by Django 5.1.2 on 2024-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
