# Generated by Django 5.1.2 on 2024-12-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_alter_utilisateur_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='numero',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
